language: generic
sudo: required

services:
  - docker

before_script:
  - mkdir aiinput
  - cp .env.travis .env
  - cp src/.env.test src/.env

script:
  - docker-compose up -d mysql
  - docker-compose run composer install --ignore-platform-reqs
  - docker-compose run artisan key:generate
  - docker-compose run artisan migrate
  - docker-compose up -d mysql_testing
  - sleep 5
  - docker-compose run --rm phpunit
